routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\CmsContentController;
use App\Http\Controllers\FinanceCoaController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserSubMenuController;
use App\Http\Controllers\ReportLedgerController;
use App\Http\Controllers\FinanceBudgetController;
use App\Http\Controllers\FinanceSalaryController;
use App\Http\Controllers\ReportBalanceController;
use App\Http\Controllers\BalanceBeginningController;
use App\Http\Controllers\FinanceTransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    
    // user
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('profiles/reset/{id}', [UserProfileController::class, 'resetProfile']);
    Route::get('profiles/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
    Route::patch('profiles/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');
    Route::resource('profiles', UserProfileController::class);
    
    // admin
    Route::group(['middleware' => ['is_admin']], function () {

        // buatan
        Route::get('/roles/{role}/access', [UserRoleController::class, 'access']);
        
        Route::get('/report-balances', [ReportBalanceController::class, 'index']);
        Route::get('/report-balances/generate', [ReportBalanceController::class, 'generate']);
        Route::get('/report-balances/export', [ReportBalanceController::class, 'exportExcel'])->name('report-balances.exportExcel');
        
        Route::get('/report-ledgers', [ReportLedgerController::class, 'index']);
        Route::get('/report-ledgers/generate', [ReportLedgerController::class, 'generate']);
        Route::get('/report-ledgers/export', [ReportLedgerController::class, 'exportExcel'])->name('report-ledgers.exportExcel');
        
        Route::get('/finance-transactions/{id}/print', [FinanceTransactionController::class, 'print'])->name('finance-transactions.print');
        
        // // resource
        Route::resource('users', UserController::class);
        Route::resource('menus', UserMenuController::class);
        Route::resource('submenus', UserSubMenuController::class);
        Route::resource('roles', UserRoleController::class);
        Route::resource('employees', EmployeeController::class);
        Route::resource('products', ProductController::class);
        Route::resource('clients', ClientController::class);
        Route::resource('finance-coas', FinanceCoaController::class);
        Route::resource('finance-budgets', FinanceBudgetController::class);
        Route::resource('finance-transactions', FinanceTransactionController::class);
        Route::resource('finance-salaries', FinanceSalaryController::class);
        Route::resource('balance-beginnings', BalanceBeginningController::class);
        Route::resource('cms-contents', CmsContentController::class);
        
    });
    

});

app/Models/FinanceSalary.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class FinanceSalary
 *
 * @property $id
 * @property $employee_id
 * @property $nama_pegawai
 * @property $gaji
 * @property $insentif
 * @property $tanggal
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class FinanceSalary extends Model
{
    
    static $rules = [
		'employee_id' => 'required',
		'nama_pegawai' => 'required',
    ];

    protected $perPage = 10;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['employee_id','nama_pegawai','gaji','insentif','tanggal', 'produk_dikerjakan'];

    public function employee(){
        return $this->belongsTo('App\Models\Employee', 'employee_id', 'id');
    }



}

app/Http/Controllers/FinanceSalaryController.php
<?php

namespace App\Http\Controllers;

use App\Models\FinanceCoa;
use Illuminate\Http\Request;
use App\Models\FinanceSalary;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

/**
 * Class FinanceSalaryController
 * @package App\Http\Controllers
 */
class FinanceSalaryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            return DataTables::of(FinanceSalary::orderBy('nama_pegawai')->get())->toJson();
        }

        return view('finance-salary.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $financeSalary = new FinanceSalary();
        return view('finance-salary.create', compact('financeSalary'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(FinanceSalary::$rules);

        $req = $request->all();
        
        $req['gaji'] = preg_replace("/[^0-9.]/", "", $req['gaji']);
        $req['insentif'] = preg_replace("/[^0-9.]/", "", $req['insentif']);

        $financeSalary = FinanceSalary::create($req);

        return redirect()->route('finance-salaries.index')
            ->with('success', 'FinanceSalary created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $financeSalary = FinanceSalary::find($id);

        return view('finance-salary.show', compact('financeSalary'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $financeSalary = FinanceSalary::find($id);

        return view('finance-salary.edit', compact('financeSalary'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  FinanceSalary $financeSalary
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, FinanceSalary $financeSalary)
    {
        request()->validate(FinanceSalary::$rules);

        $req = $request->all();

        $req['gaji'] = preg_replace("/[^0-9.]/", "", $req['gaji']);
        $req['insentif'] = preg_replace("/[^0-9.]/", "", $req['insentif']);

        $financeSalary->update($req);

        return redirect()->route('finance-salaries.index')
            ->with('success', 'FinanceSalary updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id, Request $request)
    {

        if ($request->ajax()) {
            
            $financeSalary = FinanceSalary::find($id)->delete();

            return response()->json([
                'success' => true,
                'code' => 200,
                'message' => 'FinanceSalary deleted successfully'
            ], 200);            
        }

        return redirect()->route('finance-salaries.index')
            ->with('success', 'FinanceSalary deleted successfully');
    }
}

resources/views/finance-salary/create.blade.php
@extends('layouts.main')
@section('title', __('Finance Salary'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Finance Salary') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('finance-salaries.index') }}" class="text-muted text-hover-primary">{{ __('Finance Salary') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('finance-salaries.store') }}"  role="form" enctype="multipart/form-data">
							@csrf
							
							@include('finance-salary.form')

						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/finance-salary/edit.blade.php
@extends('layouts.main')
@section('title', __('Finance Salary'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Finance Salary') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('finance-salaries.index') }}" class="text-muted text-hover-primary">{{ __('Finance Salary') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('finance-salaries.update', $financeSalary->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('finance-salary.form')

                        </form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/finance-salary/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group mb-3">
            {{ Form::label('employee_id', 'Pegawai') }}
            {{ Form::select('employee_id', [($financeSalary->employee_id) ? $financeSalary->employee_id : '' => ($financeSalary->employee) ? $financeSalary->employee->name : 'Pegawai'], $financeSalary->employee_id, ['class' => 'form-control getEmployee' . ($errors->has('employee_id') ? ' is-invalid' : ''), 'placeholder' => 'Pegawai']) }}
            {!! $errors->first('employee_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('nama_pegawai') }}
            {{ Form::text('nama_pegawai', $financeSalary->nama_pegawai, ['class' => 'form-control' . ($errors->has('nama_pegawai') ? ' is-invalid' : ''), 'placeholder' => 'Nama Pegawai']) }}
            {!! $errors->first('nama_pegawai', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('gaji') }}
            {{ Form::text('gaji', $financeSalary->gaji, ['class' => 'form-control rupiah' . ($errors->has('gaji') ? ' is-invalid' : ''), 'placeholder' => 'Gaji']) }}
            {!! $errors->first('gaji', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('produk_dikerjakan') }}
            {{ Form::number('produk_dikerjakan', $financeSalary->produk_dikerjakan, ['class' => 'form-control rupiah' . ($errors->has('produk_dikerjakan') ? ' is-invalid' : ''), 'placeholder' => 'Produk Dikerjakan']) }}
            {!! $errors->first('produk_dikerjakan', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('insentif') }}
            {{ Form::text('insentif', $financeSalary->insentif, ['class' => 'form-control rupiah' . ($errors->has('insentif') ? ' is-invalid' : ''), 'placeholder' => 'Insentif']) }}
            {!! $errors->first('insentif', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-3">
            {{ Form::label('tanggal') }}
            {{ Form::text('tanggal', $financeSalary->tanggal, ['class' => 'form-control datepicker' . ($errors->has('tanggal') ? ' is-invalid' : ''), 'placeholder' => 'Tanggal']) }}
            {!! $errors->first('tanggal', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            getEmployee();
            rupiahClass();
        });

        rupiahClass();
    </script>

    {{-- event --}}
    <script type="text/javascript">
        $('.getEmployee').on('change', function(){

            var id = $(this).val();
            $.ajax({
                url: `{{route('api.getEmployeeValues')}}`,
                method: 'get',
                data: {id: id},
                success: function(response){
                    $('input[name="nama_pegawai"]').val(response.name);                    
                }
            });

            //gaji
            $.ajax({
                url: `{{route('api.getSalaryValues')}}`,
                method: 'get',
                success: function(response){

                    //rumus gaji
                    var gaji = (response.gaji * 40/100) / response.jumlahPegawai;
                    gaji = gaji.toFixed(2);

                    $('input[name="gaji"]').val(rupiah2(gaji));
                    
                }
            });

        });

        $('input[name="produk_dikerjakan"]').on('keyup', function(){
            $.ajax({
                url: `{{route('api.getInsentif')}}`,
                method: 'get',
                success: function(response){
                    
                    //rumus gaji
                    var produkDikerjakan = $('input[name="produk_dikerjakan"]').val();
                    var insentif = (response.pendapatan * 30/100) / 5 * produkDikerjakan;
                    insentif = insentif.toFixed(2);

                    $('input[name="insentif"]').val(rupiah2(insentif));

                }
            });
        });

    </script>

    {{-- function --}}
    <script type="text/javascript">
        function getEmployee(){
            $(".getEmployee").select2({
                width: '100%',
                ajax: {
                    url: `{{route('api.getEmployee')}}`,
                    dataType: 'json'
                }
            });
        }
    </script>
@endsection

resources/views/finance-salary/index.blade.php
@extends('layouts.main')
@section('title', __('Finance Salary'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ route('finance-salaries.index') }}" class="text-muted text-hover-primary">{{ __('Finance Salary') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Finance Salary') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<!--begin::Alert-->                                        
					
					<!--end::Alert-->
						<div class="table-responsive">
							<a href="{{ route('finance-salaries.create') }}" class="btn btn-primary mb-3" >Tambah {{ __('Finance Salary') }} Baru</a>
							@if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
							<table id="dataTable" class="table table-row-bordered gy-5">
							</table>
						</div>
					</div>
                </div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">

		$(document).ready(function(){
            var table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
				ajax: {
					url: "{{ route('finance-salaries.index') }}", 
					data: function ( d ) {
						d.test = 1;
					}
				},
                columns: 
				[
					{ 
						title: 'No',
						class: 'text-center',
                        data: 'id',
                        name: 'id'
                    },
					{ 
						title: 'Nama Pegawai',
                        data: 'nama_pegawai',
                        name: 'nama_pegawai'
                    },
					{ 
						title: 'Gaji',
                        data: 'gaji',
                        name: 'gaji',
						render: function(r) {
                            var data = rupiah2(r);
                            return 'Rp. <span style="float:right;">'+ data +'</span>';
                        }
                    },
					{ 
						title: 'Insentif',
                        data: 'insentif',
                        name: 'insentif',
						render: function(r) {
                            var data = rupiah2(r);
                            return 'Rp. <span style="float:right;">'+ data +'</span>';
                        }
                    },
					{ 
						title: 'THP',
                        data: 'insentif',
                        name: 'thp',
						render: function(id, display, data) {
                            var data = rupiah2(Number(data.gaji) + Number(data.insentif));
                            return 'Rp. <span style="float:right;">'+ data +'</span>';
                        }
                    },
					{ 
						title: 'Tanggal Dibayar',
                        data: 'tanggal',
                        name: 'tanggal'
                    },
					{
                        title: 'Action',
                        class: 'text-center',
                        data: 'id',
                        render: function(id, display, data) {
                            return `
                                <form action="{{ route('finance-salaries.index') }}`+'/'+id+`" method="POST">
									<a class="btn btn-sm btn-primary " href="{{ route('finance-salaries.index') }}`+'/'+id+`"><i class="fa fa-fw fa-eye"></i> Show</a>
									<a class="btn btn-sm btn-success" href="{{ route('finance-salaries.index') }}`+'/'+id+ '/edit'+`"><i class="fa fa-fw fa-edit"></i> Edit</a>
									@csrf 
									@method('DELETE')
									<button type="submit" class="btn btn-danger btn-sm btn-delete" data-name="${data.nama_pegawai}"><i class="fa fa-fw fa-trash"></i> Delete</button>
								</form>
                            `;
                        }
                    },
                ],
				order: [1, 'asc']
            });

			table.on( 'draw.dt', function () {
                var info = table.page.info();
                var i = 0;
                for (let x = (info.start + 1); x <= info.end; x++) {
                    table.column(0).nodes()[i].innerHTML = x;
                    i++;
                }
            } ).draw();

			$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

				var form = $(this).closest('form');

				var data = $(this).data('name');

				Swal.fire({
					title: 'Are you sure?',
					text: data + " will be deleted permanently!" ,
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'Yes, delete it!'
				}).then((result) => {
					if (result.isConfirmed) {

						$.ajax({
							type: form.attr('method'),
							url: form.attr('action'),
							data: form.serialize(),
							beforeSend: function(){
								Swal.fire({
									icon: 'info',
									title: 'Please wait....',
								});
							},
							success: function (r) {
								Swal.fire({
									icon: 'success',
									title: r.message
								});
								
								table.ajax.reload();
							},
							error: function (e) {
								Swal.fire({
									icon: 'error',
									title: 'An error occurred.'
								});
							},
						});
					}else{

						Swal.fire({
							icon: 'error',
							title: 'Operation canceled!'
						});
					}
				})


			});

        });

		

	</script>
@endsection

resources/views/finance-salary/show.blade.php
@extends('layouts.main')
@section('title', __('Finance Salary'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ route('finance-salaries.index') }}" class="text-muted text-hover-primary">{{ __('Finance Salary') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Finance Salary') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
                <div class="card">
                    <div class="card-header">
                        <div class="float-left mt-4">
                            <span class="card-title">Show Finance Salary</span>
                        </div>
                        <div class="float-right mt-4">
                            <a class="btn btn-primary" href="{{ route('finance-salaries.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Employee Id:</strong>
                            {{ $financeSalary->employee_id }}
                        </div>
                        <div class="form-group">
                            <strong>Nama Pegawai:</strong>
                            {{ $financeSalary->nama_pegawai }}
                        </div>
                        <div class="form-group">
                            <strong>Gaji:</strong>
                            {{ $financeSalary->gaji }}
                        </div>
                        <div class="form-group">
                            <strong>Insentif:</strong>
                            {{ $financeSalary->insentif }}
                        </div>
                        <div class="form-group">
                            <strong>Tanggal:</strong>
                            {{ $financeSalary->tanggal }}
                        </div>

                    </div>
                </div>
            <!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection