routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\CmsContentController;
use App\Http\Controllers\FinanceCoaController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserSubMenuController;
use App\Http\Controllers\ReportLedgerController;
use App\Http\Controllers\FinanceBudgetController;
use App\Http\Controllers\FinanceSalaryController;
use App\Http\Controllers\ReportBalanceController;
use App\Http\Controllers\BalanceBeginningController;
use App\Http\Controllers\FinanceTransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    
    // user
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('profiles/reset/{id}', [UserProfileController::class, 'resetProfile']);
    Route::get('profiles/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
    Route::patch('profiles/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');
    Route::resource('profiles', UserProfileController::class);
    
    // admin
    Route::group(['middleware' => ['is_admin']], function () {

        // buatan
        Route::get('/roles/{role}/access', [UserRoleController::class, 'access']);
        
        Route::get('/report-balances', [ReportBalanceController::class, 'index']);
        Route::get('/report-balances/generate', [ReportBalanceController::class, 'generate']);
        Route::get('/report-balances/export', [ReportBalanceController::class, 'exportExcel'])->name('report-balances.exportExcel');
        
        Route::get('/report-ledgers', [ReportLedgerController::class, 'index']);
        Route::get('/report-ledgers/generate', [ReportLedgerController::class, 'generate']);
        Route::get('/report-ledgers/export', [ReportLedgerController::class, 'exportExcel'])->name('report-ledgers.exportExcel');
        
        Route::get('/finance-transactions/{id}/print', [FinanceTransactionController::class, 'print'])->name('finance-transactions.print');
        
        // // resource
        Route::resource('users', UserController::class);
        Route::resource('menus', UserMenuController::class);
        Route::resource('submenus', UserSubMenuController::class);
        Route::resource('roles', UserRoleController::class);
        Route::resource('employees', EmployeeController::class);
        Route::resource('products', ProductController::class);
        Route::resource('clients', ClientController::class);
        Route::resource('finance-coas', FinanceCoaController::class);
        Route::resource('finance-budgets', FinanceBudgetController::class);
        Route::resource('finance-transactions', FinanceTransactionController::class);
        Route::resource('finance-salaries', FinanceSalaryController::class);
        Route::resource('balance-beginnings', BalanceBeginningController::class);
        Route::resource('cms-contents', CmsContentController::class);
        
    });
    

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Product
 *
 * @property $id
 * @property $client_id
 * @property $image
 * @property $name
 * @property $description
 * @property $order_date
 * @property $order_finish_date
 * @property $status
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Product extends Model
{
  protected $with = ['client'];

  static $rules = [
    'client_id' => 'required',
    // 'image' => 'required',
    'name' => 'required|min:3|max:50|regex:/^[a-zA-Z\s]+$/',
    'description' => 'required|string|min:5',
    'order_date' => 'required|date_format:Y-m-d|before_or_equal:today',
    'order_finish_date' => 'required|date_format:Y-m-d',
    'status' => 'required',
  ];

  public function client()
  {
    return $this->belongsTo(Client::class);
  }

  protected $perPage = 10;

  /**
   * Attributes that should be mass-assignable.
   *
   * @var array
   */
  protected $fillable = ['client_id', 'image', 'name', 'description', 'order_date', 'order_finish_date', 'status'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;


/**
 * Class ProductController
 * @package App\Http\Controllers
 */
class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            return DataTables::of(Product::all())->toJson();
        }

        return view('product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = new Product();
        $clients = Client::all();
        return view('product.create', compact('product', 'clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = Product::$rules;
        $rules['image'] = 'required|image|file|max:2048';

        request()->validate($rules);

        $validatedData['client_id'] = $request->client_id;
        $validatedData['image'] = $request->file('image')->store('user-images');
        $validatedData['name'] = $request->name;
        $validatedData['description'] = $request->description;
        $validatedData['order_date'] = $request->order_date;
        $validatedData['order_finish_date'] = $request->order_finish_date;
        $validatedData['status'] = $request->status;

        $product = Product::create($validatedData);

        return redirect()->route('products.index')
            ->with('success', 'Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);

        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        $clients = Client::where('id', '!=', $product->client_id)->get();

        return view('product.edit', compact('product', 'clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $rules = Product::$rules;

        if ($request->file('image')) {
            $rules['image'] = 'required|image|file|max:2048';
        }

        request()->validate($rules);

        if ($request->file('image')) {
            if ($request->oldImage) {
                Storage::delete($request->oldImage);
            }
            $validatedData['image'] = $request->file('image')->store('user-images');
        }

        $validatedData['client_id'] = $request->client_id;
        $validatedData['name'] = $request->name;
        $validatedData['description'] = $request->description;
        $validatedData['order_date'] = $request->order_date;
        $validatedData['order_finish_date'] = $request->order_finish_date;
        $validatedData['status'] = $request->status;

        $product->update($validatedData);

        return redirect()->route('products.index')
            ->with('success', 'Product updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        Storage::delete($product->image);
        $product->delete();

        return redirect()->route('products.index')
            ->with('success', 'Product deleted successfully');
    }
}

resources/views/product/create.blade.php
@extends('layouts.main')
@section('title', __('Product'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Product') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('products.index') }}" class="text-muted text-hover-primary">{{ __('Product') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('products.store') }}"  role="form" enctype="multipart/form-data">
							@csrf
							
							@include('product.form')

						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/product/edit.blade.php
@extends('layouts.main')
@section('title', __('Product'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Product') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('products.index') }}" class="text-muted text-hover-primary">{{ __('Product') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Edit</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('products.update', $product->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('product.form')

                        </form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/product/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        {{ Form::hidden('oldImage', $product->image) }}
        <div class="form-group mb-5">
            {{ Form::label('client', '', ['class' => 'mb-4']) }}
            <select name="client_id" id="client" class="form-select form-select-solid {{ $errors->has('client_id') ? ' is-invalid' : '' }}" data-control="select2" data-placeholder="Select an option" data-hide-search="true" data-allow-clear="true">
                <option value=""></option>
                @if ($product->client_id)
                    <option value="{{ $product->client_id }}" selected>{{ $product->client->name }}</option>
                @endif
                @foreach ($clients as $client)
                    <option value="{{ $client->id }}">{{ $client->name }}</option>
                @endforeach
            </select>
            {!! $errors->first('client_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('image', '', ['class' => 'd-block']) }}
            <div class="row m-0">
                <div class="col-md-4 py-3">
                    <div class="d-flex align-items-center">
                        @if ($product->image)
                            <img src="{{ URL::asset('storage') }}/{{ $product->image }}" alt="{{ $product->image }}" id="image-profile" width="100px">
                        @else
                            <img src="" alt="" id="image-profile" width="100px">
                        @endif
                        <div class="d-none fw-bolder text-dark ms-7" id="text-preview">
                            <span class="d-block small">*Recommended ratio: 1:1</span>
                            <span class="d-block small">*Max image size: 2Mb</span>
                            <span class="d-block small">*Type of file must an image</span>
                        </div>
                    </div>
                </div>
            </div>
            {{ Form::file('image', ['class' => 'form-control' . ($errors->has('image') ? ' is-invalid' : ''), 'onchange' => 'previewImage()']) }}
            {!! $errors->first('image', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('name', '', ['class' => 'mb-4']) }}
            {{ Form::text('name', $product->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => 'Name']) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('description', '', ['class' => 'mb-4']) }}
            {{ Form::textarea('description', $product->description, ['class' => 'form-control' . ($errors->has('description') ? ' is-invalid' : ''), 'placeholder' => 'Description', 'rows' => '5']) }}
            {!! $errors->first('description', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('order_date', '', ['class' => 'mb-4']) }}
            {{ Form::text('order_date', $product->order_date, ['class' => 'form-control' . ($errors->has('order_date') ? ' is-invalid' : ''), 'placeholder' => 'Order Date']) }}
            {!! $errors->first('order_date', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('order_finish_date', '', ['class' => 'mb-4']) }}
            {{ Form::text('order_finish_date', $product->order_finish_date, ['class' => 'form-control' . ($errors->has('order_finish_date') ? ' is-invalid' : ''), 'placeholder' => 'Order Finish Date']) }}
            {!! $errors->first('order_finish_date', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('status', '', ['class' => 'mb-4']) }}
            {{ Form::select('status', [($product->status) ? $product->status : '' => '', 'P' => 'On Progress', 'D' => 'Done', 'M' => 'Maintenance', 'R' => 'Rejected'], '', ['class' => 'form-select form-select-solid' . ($errors->has('status') ? ' is-invalid' : ''), 'data-control' => 'select2', 'data-placeholder' => 'Select an option', 'data-allow-clear' => 'true', 'data-hide-search' => 'true']) }}
            {!! $errors->first('status', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/product/index.blade.php
@extends('layouts.main')
@section('title', __('Product'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Product') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<a href="{{ route('products.create') }}" class="btn btn-primary mb-3" >Tambah {{ __('Product') }} Baru</a>
						<!--begin::Alert-->                                        
						@if ($message = Session::get('success'))
							<div class="alert alert-success">
								<p>{{ $message }}</p>
							</div>
						@endif
						<!--end::Alert-->
						<div class="table-responsive">
							{{-- <table class="table table-striped table-hover gy-7 gs-10 text-center align-middle">
								<thead>
									<tr class="fw-bold fs-6 text-gray-800 border-bottom-2 border-gray-200">
										<th>No</th>
										
										<th>Client</th>
										<th>Image</th>
										<th>Name</th>
										<th>Description</th>
										<th>Order Date</th>
										<th>Order Finish Date</th>
										<th>Status</th>

										<th>Aksi</th>
									</tr>
								</thead>
								<tbody>                                                 
                                    @foreach ($products as $product)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $product->client->name }}</td>
											<td><img src="{{ URL::asset('storage') }}/{{ $product->image }}" alt="{{ $product->image }}" width="100px"></td>
											<td>{{ $product->name }}</td>
											<td>{{ Str::limit($product->description, 20) }}</td>
											<td>{{ $product->order_date }}</td>
											<td>{{ $product->order_finish_date }}</td>
											<td>{!! ($product->status == "P") ? '<span class="bullet bullet-dot bg-primary h-15px w-15px"></span>' : (($product->status == "D") ? '<i class="bi bi-check2-all fs-2 text-success"></i>' : (($product->status == "M") ? '<span class="bullet bullet-dot bg-warning h-15px w-15px"></span>' : (($product->status == "R") ? '<i class="fas fa-times fs-2 text-danger"></i>' : ''))) !!}</td>

                                            <td>
                                                <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('products.show',$product->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('products.edit',$product->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
								</tbody>
							</table> --}}

							<table id="dataTable" class="table table-row-bordered gy-5">
							</table>
						</div>
					</div>
                </div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">


		$(document).ready(function(){
            var table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
				ajax: {
					url: "{{ route('products.index') }}", 
					data: function ( d ) {
						d.test = 1;
					}
				},
                columns: 
				[
					{ 
						title: 'No',
						class: 'text-center',
                        data: 'id',
                        name: 'id'
                    },
					{
                        title: 'Image',
                        class: 'text-center',
                        data: 'image',
                        render: function(image, display, data) {
						    return `
                                <td><img src="{{ URL::asset('storage') }}/${image}" alt="" width="100px"></td>
                            `;
                        }
                    },
					{ 
						title: 'Nama Produk',
						class: 'text-center',
                        data: 'name',
                        name: 'name'
                    },
					{
                        title: 'Deskripsi',
                        class: 'text-center',
                        data: 'description',
                        render: function(description, display, data) {
						    return `
                                <td>{{ Str::limit(` + description + `, 20) }}</td>
                            `;
                        }
                    },
					{ 
						title: 'Tanggal Order',
						class: 'text-center',
                        data: 'order_date',
                        name: 'order_date'
                    },
					{ 
						title: 'Tanggal Selesai Order',
						class: 'text-center',
                        data: 'order_finish_date',
                        name: 'order_finish_date'
                    },
					{
                        title: 'Status',
                        class: 'text-center',
                        data: 'status',
                        render: function(status, display, data) {
						    return `
								<td>{!! (` + status + ` == "P") ? '<span class="bullet bullet-dot bg-primary h-15px w-15px"></span>' : ((` + status + ` == "D") ? '<i class="bi bi-check2-all fs-2 text-success"></i>' : ((` + status + ` == "M") ? '<span class="bullet bullet-dot bg-warning h-15px w-15px"></span>' : ((` + status + ` == "R") ? '<i class="fas fa-times fs-2 text-danger"></i>' : ''))) !!}</td>
                            `;
                        }
                    },
					{
                        title: 'Action',
                        class: 'text-center',
                        data: 'id',
                        render: function(id, display, data) {
                            return `
                                <form action="{{ route('products.destroy','') }}`+'/'+id+`" method="POST">
									<a class="btn btn-sm btn-primary " href="{{ route('products.index') }}`+'/'+id+`"><i class="fa fa-fw fa-eye"></i> Show</a>
									<a class="btn btn-sm btn-success" href="{{ route('products.index') }}`+'/'+id+ '/edit'+`"><i class="fa fa-fw fa-edit"></i> Edit</a>
									@csrf 
									@method('DELETE')
									<button type="submit" class="btn btn-danger btn-sm btn-delete" data-name="${data.name}"><i class="fa fa-fw fa-trash"></i> Delete</button>
								</form>
                            `;
                        }
                    },
                ]
            });

			table.on( 'draw.dt', function () {
                var info = table.page.info();
                var i = 0;
                for (let x = (info.start + 1); x <= info.end; x++) {
                    table.column(0).nodes()[i].innerHTML = x;
                    i++;
                }
            } ).draw();

			$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

				var form = $(this).closest('form');

				var data = $(this).data('name');

				Swal.fire({
					title: 'Are you sure?',
					text: data + " will be deleted permanently!" ,
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'Yes, delete it!'
				}).then((result) => {
					if (result.isConfirmed) {

						$.ajax({
							type: form.attr('method'),
							url: form.attr('action'),
							data: form.serialize(),
							beforeSend: function(){
								Swal.fire({
									icon: 'info',
									title: 'Please wait....',
								});
							},
							success: function (r) {
								Swal.fire({
									icon: 'success',
									title: r.message
								});
								
								table.ajax.reload();
							},
							error: function (e) {
								Swal.fire({
									icon: 'error',
									title: 'An error occurred.'
								});
							},
						});
					}else{

						Swal.fire({
							icon: 'error',
							title: 'Operation canceled!'
						});
					}
				})


			});

        });

		

	</script>
@endsection