routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\CmsContentController;
use App\Http\Controllers\FinanceCoaController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserSubMenuController;
use App\Http\Controllers\ReportLedgerController;
use App\Http\Controllers\FinanceBudgetController;
use App\Http\Controllers\FinanceSalaryController;
use App\Http\Controllers\ReportBalanceController;
use App\Http\Controllers\BalanceBeginningController;
use App\Http\Controllers\FinanceTransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    
    // user
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('profiles/reset/{id}', [UserProfileController::class, 'resetProfile']);
    Route::get('profiles/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
    Route::patch('profiles/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');
    Route::resource('profiles', UserProfileController::class);
    
    // admin
    Route::group(['middleware' => ['is_admin']], function () {

        // buatan
        Route::get('/roles/{role}/access', [UserRoleController::class, 'access']);
        
        Route::get('/report-balances', [ReportBalanceController::class, 'index']);
        Route::get('/report-balances/generate', [ReportBalanceController::class, 'generate']);
        Route::get('/report-balances/export', [ReportBalanceController::class, 'exportExcel'])->name('report-balances.exportExcel');
        
        Route::get('/report-ledgers', [ReportLedgerController::class, 'index']);
        Route::get('/report-ledgers/generate', [ReportLedgerController::class, 'generate']);
        Route::get('/report-ledgers/export', [ReportLedgerController::class, 'exportExcel'])->name('report-ledgers.exportExcel');
        
        Route::get('/finance-transactions/{id}/print', [FinanceTransactionController::class, 'print'])->name('finance-transactions.print');
        
        // // resource
        Route::resource('users', UserController::class);
        Route::resource('menus', UserMenuController::class);
        Route::resource('submenus', UserSubMenuController::class);
        Route::resource('roles', UserRoleController::class);
        Route::resource('employees', EmployeeController::class);
        Route::resource('products', ProductController::class);
        Route::resource('clients', ClientController::class);
        Route::resource('finance-coas', FinanceCoaController::class);
        Route::resource('finance-budgets', FinanceBudgetController::class);
        Route::resource('finance-transactions', FinanceTransactionController::class);
        Route::resource('finance-salaries', FinanceSalaryController::class);
        Route::resource('balance-beginnings', BalanceBeginningController::class);
        Route::resource('cms-contents', CmsContentController::class);
        
    });
    

});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Employee
 *
 * @property $id
 * @property $image
 * @property $email
 * @property $position
 * @property $name
 * @property $place_of_birth
 * @property $date_of_birth
 * @property $phone
 * @property $address
 * @property $join_date
 * @property $remember_token
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Employee extends Model
{

  static $rules = [
    // 'image' => 'required|image|file|max:2048',
    // 'email' => 'required|email:rfc,dns|unique:employees,email',
    'position' => 'required|regex:/^[a-zA-Z\s]+$/',
    'name' => 'required|min:3|max:50|regex:/^[a-zA-Z\s]+$/',
    'place_of_birth' => 'required|regex:/^[a-zA-Z\s]+$/',
    'date_of_birth' => 'required|date_format:Y-m-d|before_or_equal:-16 years|after_or_equal:-60 years',
    'phone' => 'required|numeric|digits_between:10,12',
    'address' => 'required|string|min:5',
    'join_date' => 'required|date_format:Y-m-d|before_or_equal:today',
  ];

  protected $perPage = 10;

  /**
   * Attributes that should be mass-assignable.
   *
   * @var array
   */
  protected $fillable = ['image', 'email', 'position', 'name', 'place_of_birth', 'date_of_birth', 'phone', 'address', 'join_date'];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;

/**
 * Class EmployeeController
 * @package App\Http\Controllers
 */
class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return DataTables::of(Employee::all())->toJson();
        }

        $employees = Employee::paginate();


        return view('employee.index', compact('employees'))
            ->with('i', (request()->input('page', 1) - 1) * $employees->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employee = new Employee();
        return view('employee.create', compact('employee'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = Employee::$rules;
        $rules['image'] = 'required|image|file|max:2048';
        $rules['email'] = 'required|email:rfc,dns|unique:employees,email';

        request()->validate($rules);

        $validatedData['image'] = $request->file('image')->store('user-images');
        $validatedData['email'] = $request->email;
        $validatedData['position'] = $request->position;
        $validatedData['name'] = $request->name;
        $validatedData['place_of_birth'] = $request->place_of_birth;
        $validatedData['date_of_birth'] = $request->date_of_birth;
        $validatedData['phone'] = $request->phone;
        $validatedData['address'] = $request->address;
        $validatedData['join_date'] = $request->join_date;
        $employee = Employee::create($validatedData);

        return redirect()->route('employees.index')
            ->with('success', 'Employee created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);

        return view('employee.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);

        return view('employee.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $rules = Employee::$rules;
        if ($request->email != $employee->email) {
            $rules['email'] = 'required|email:rfc,dns|unique:employees,email';
        } else {
            $rules['email'] = 'required|email:rfc,dns';
        }

        if ($request->file('image')) {
            $rules['image'] = 'required|image|file|max:2048';
        }

        request()->validate($rules);

        if ($request->file('image')) {
            if ($request->oldImage) {
                Storage::delete($request->oldImage);
            }
            $validatedData['image'] = $request->file('image')->store('user-images');
        }

        $validatedData['email'] = $request->email;
        $validatedData['position'] = $request->position;
        $validatedData['name'] = $request->name;
        $validatedData['place_of_birth'] = $request->place_of_birth;
        $validatedData['date_of_birth'] = $request->date_of_birth;
        $validatedData['phone'] = $request->phone;
        $validatedData['address'] = $request->address;
        $validatedData['join_date'] = $request->join_date;

        $employee->update($validatedData);

        return redirect()->route('employees.index')
            ->with('success', 'Employee updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        Storage::delete($employee->image);
        $employee->delete();

        return redirect()->route('employees.index')
            ->with('success', 'Employee deleted successfully');
    }
}

resources/views/employee/create.blade.php
@extends('layouts.main')
@section('title', __('Employee'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Employee') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('employees.index') }}" class="text-muted text-hover-primary">{{ __('Employee') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('employees.store') }}"  role="form" enctype="multipart/form-data">
							@csrf
							
							@include('employee.form')

						</form>
					</div>
				</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.main')
@section('title', __('Employee'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Employee') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('employees.index') }}" class="text-muted text-hover-primary">{{ __('Employee') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Edit</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('employees.update', $employee->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('employee.form')

                        </form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/employee/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        {{ Form::hidden('oldImage', $employee->image) }}
        <div class="form-group mb-5">
            {{ Form::label('image', '', ['class' => 'd-block']) }}
            <div class="row m-0">
                <div class="col-md-4 py-3">
                    <div class="d-flex align-items-center">
                        @if ($employee->image)
                            <img src="{{ URL::asset('storage') }}/{{ $employee->image }}" alt="{{ $employee->image }}" id="image-profile" width="100px">
                        @else
                            <img src="" alt="" id="image-profile" width="100px">
                        @endif
                        <div class="d-none fw-bolder text-dark ms-7" id="text-preview">
                            <span class="d-block small">*Recommended ratio: 1:1</span>
                            <span class="d-block small">*Max image size: 2Mb</span>
                            <span class="d-block small">*Type of file must an image</span>
                        </div>
                    </div>
                </div>
            </div>
            {{ Form::file('image', ['class' => 'form-control' . ($errors->has('image') ? ' is-invalid' : ''), 'onchange' => 'previewImage()']) }}
            {!! $errors->first('image', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('email', '', ['class' => 'mb-4']) }}
            {{ Form::text('email', $employee->email, ['class' => 'form-control' . ($errors->has('email') ? ' is-invalid' : ''), 'placeholder' => 'Email']) }}
            {!! $errors->first('email', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('position', '', ['class' => 'mb-4']) }}
            {{ Form::text('position', $employee->position, ['class' => 'form-control' . ($errors->has('position') ? ' is-invalid' : ''), 'placeholder' => 'Position']) }}
            {!! $errors->first('position', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('name', '', ['class' => 'mb-4']) }}
            {{ Form::text('name', $employee->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => 'Name']) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('place_of_birth', '', ['class' => 'mb-4']) }}
            {{ Form::text('place_of_birth', $employee->place_of_birth, ['class' => 'form-control' . ($errors->has('place_of_birth') ? ' is-invalid' : ''), 'placeholder' => 'Place Of Birth']) }}
            {!! $errors->first('place_of_birth', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('date_of_birth', '', ['class' => 'mb-4']) }}
            {{ Form::text('date_of_birth', $employee->date_of_birth, ['class' => 'form-control' . ($errors->has('date_of_birth') ? ' is-invalid' : ''), 'placeholder' => 'Date Of Birth', 'id' => 'date_of_birth']) }}
            {!! $errors->first('date_of_birth', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('phone', '', ['class' => 'mb-4']) }}
            {{ Form::text('phone', $employee->phone, ['class' => 'form-control' . ($errors->has('phone') ? ' is-invalid' : ''), 'placeholder' => 'Phone']) }}
            {!! $errors->first('phone', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('address', '', ['class' => 'mb-4']) }}
            {{ Form::textarea('address', $employee->address, ['class' => 'form-control' . ($errors->has('address') ? ' is-invalid' : ''), 'placeholder' => 'Address', 'rows' => '5']) }}
            {!! $errors->first('address', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group mb-5">
            {{ Form::label('join_date', '', ['class' => 'mb-4']) }}
            {{ Form::text('join_date', $employee->join_date, ['class' => 'form-control' . ($errors->has('join_date') ? ' is-invalid' : ''), 'placeholder' => 'Join Date', 'id' => 'join_date']) }}
            {!! $errors->first('join_date', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/employee/index.blade.php
@extends('layouts.main')
@section('title', __('Employee'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Employee') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<a href="{{ route('employees.create') }}" class="btn btn-primary mb-3" >Tambah {{ __('Employee') }} Baru</a>
						<!--begin::Alert-->
						@if ($message = Session::get('success'))
						<div class="alert alert-success">
							<p>{{ $message }}</p>
						</div>
						@endif
						<!--end::Alert-->
						<div class="table-responsive">
							{{-- <table class="table table-striped table-hover gy-7 gx-10 text-center align-middle">
								<thead>
									<tr class="fw-bold fs-6 text-gray-800 border-bottom-2 border-gray-200">
										<th>No</th>
										<th>Image</th>
										<th>Email</th>
										<th>Position</th>
										<th>Name</th>
										<th>Place Of Birth</th>
										<th>Date Of Birth</th>
										<th>Phone</th>
										<th>Address</th>
										<th>Join Date</th>
										<th>Aksi</th>
									</tr>
								</thead>
								<tbody>                                                 
									@foreach ($employees as $employee)
										<tr>
											<td>{{ ++$i }}</td>
											
											<td><img src="{{ URL::asset('storage') }}/{{ $employee->image }}" alt="{{ $employee->image }}" width="100px"></td>
											<td>{{ $employee->email }}</td>
											<td>{{ $employee->position }}</td>
											<td>{{ $employee->name }}</td>
											<td>{{ $employee->place_of_birth }}</td>
											<td>{{ $employee->date_of_birth }}</td>
											<td>{{ $employee->phone }}</td>
											<td>{{ $employee->address }}</td>
											<td>{{ $employee->join_date }}</td>

											<td>
												<form action="{{ route('employees.destroy',$employee->id) }}" method="POST">
													<a class="btn btn-sm btn-primary " href="{{ route('employees.show',$employee->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
													<a class="btn btn-sm btn-success" href="{{ route('employees.edit',$employee->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
													@csrf
													@method('DELETE')
													<button type="submit" class="btn btn-danger btn-sm btn-delete"><i class="fa fa-fw fa-trash"></i> Delete</button>
												</form>
											</td>
										</tr>
									@endforeach
								</tbody>
							</table> --}}

							<table id="dataTable" class="table table-row-bordered gy-5">
							</table>
						</div>
					</div>
                </div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">


		$(document).ready(function(){
            var table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
				ajax: {
					url: "{{ route('employees.index') }}", 
					data: function ( d ) {
						d.test = 1;
					}
				},
                columns: 
				[
					{ 
						title: 'No',
						class: 'text-center',
                        data: 'id',
                        name: 'id'
                    },
					{
                        title: 'Image',
                        class: 'text-center',
                        data: 'image',
                        render: function(image, display, data) {
						    return `
                                <td><img src="{{ URL::asset('storage') }}/${image}" alt="" width="100px"></td>
                            `;
                        }
                    },
					{ 
						title: 'Email',
						class: 'text-center',
                        data: 'email',
                        name: 'email'
                    },
					{ 
						title: 'Position',
						class: 'text-center',
                        data: 'position',
                        name: 'position'
                    },
					{ 
						title: 'Nama',
						class: 'text-center',
                        data: 'name',
                        name: 'name'
                    },
					{ 
						title: 'Tempat Lahir',
						class: 'text-center',
                        data: 'place_of_birth',
                        name: 'place_of_birth'
                    },
					{ 
						title: 'Tanggal Lahir',
						class: 'text-center',
                        data: 'date_of_birth',
                        name: 'date_of_birth'
                    },
					{ 
						title: 'Telp',
						class: 'text-center',
                        data: 'phone',
                        name: 'phone'
                    },
					{ 
						title: 'Alamat',
						class: 'text-center',
                        data: 'address',
                        name: 'address'
                    },
					{ 
						title: 'Tanggal Bergabung',
						class: 'text-center',
                        data: 'join_date',
                        name: 'join_date'
                    },
					{
                        title: 'Action',
                        class: 'text-center',
                        data: 'id',
                        render: function(id, display, data) {
                            return `
                                <form action="{{ route('employees.destroy','') }}`+'/'+id+`" method="POST">
									<a class="btn btn-sm btn-primary " href="{{ route('employees.index') }}`+'/'+id+`"><i class="fa fa-fw fa-eye"></i> Show</a>
									<a class="btn btn-sm btn-success" href="{{ route('employees.index') }}`+'/'+id+ '/edit'+`"><i class="fa fa-fw fa-edit"></i> Edit</a>
									@csrf 
									@method('DELETE')
									<button type="submit" class="btn btn-danger btn-sm btn-delete" data-name="${data.name}"><i class="fa fa-fw fa-trash"></i> Delete</button>
								</form>
                            `;
                        }
                    },
                ]
            });

			table.on( 'draw.dt', function () {
                var info = table.page.info();
                var i = 0;
                for (let x = (info.start + 1); x <= info.end; x++) {
                    table.column(0).nodes()[i].innerHTML = x;
                    i++;
                }
            } ).draw();

			$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

				var form = $(this).closest('form');

				var data = $(this).data('name');

				Swal.fire({
					title: 'Are you sure?',
					text: data + " will be deleted permanently!" ,
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'Yes, delete it!'
				}).then((result) => {
					if (result.isConfirmed) {

						$.ajax({
							type: form.attr('method'),
							url: form.attr('action'),
							data: form.serialize(),
							beforeSend: function(){
								Swal.fire({
									icon: 'info',
									title: 'Please wait....',
								});
							},
							success: function (r) {
								Swal.fire({
									icon: 'success',
									title: r.message
								});
								
								table.ajax.reload();
							},
							error: function (e) {
								Swal.fire({
									icon: 'error',
									title: 'An error occurred.'
								});
							},
						});
					}else{

						Swal.fire({
							icon: 'error',
							title: 'Operation canceled!'
						});
					}
				})


			});

        });

		

	</script>
@endsection