routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UserMenuController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\CmsContentController;
use App\Http\Controllers\FinanceCoaController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserSubMenuController;
use App\Http\Controllers\ReportLedgerController;
use App\Http\Controllers\FinanceBudgetController;
use App\Http\Controllers\FinanceSalaryController;
use App\Http\Controllers\ReportBalanceController;
use App\Http\Controllers\BalanceBeginningController;
use App\Http\Controllers\FinanceTransactionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    
    // user
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('profiles/reset/{id}', [UserProfileController::class, 'resetProfile']);
    Route::get('profiles/change-password', [UserProfileController::class, 'changePassword'])->name('change-password.index');
    Route::patch('profiles/change-password/{id}', [UserProfileController::class, 'changeProccess'])->name('profile.change-password');
    Route::resource('profiles', UserProfileController::class);
    
    // admin
    Route::group(['middleware' => ['is_admin']], function () {

        // buatan
        Route::get('/roles/{role}/access', [UserRoleController::class, 'access']);
        
        Route::get('/report-balances', [ReportBalanceController::class, 'index']);
        Route::get('/report-balances/generate', [ReportBalanceController::class, 'generate']);
        Route::get('/report-balances/export', [ReportBalanceController::class, 'exportExcel'])->name('report-balances.exportExcel');
        
        Route::get('/report-ledgers', [ReportLedgerController::class, 'index']);
        Route::get('/report-ledgers/generate', [ReportLedgerController::class, 'generate']);
        Route::get('/report-ledgers/export', [ReportLedgerController::class, 'exportExcel'])->name('report-ledgers.exportExcel');
        
        Route::get('/finance-transactions/{id}/print', [FinanceTransactionController::class, 'print'])->name('finance-transactions.print');
        
        // // resource
        Route::resource('users', UserController::class);
        Route::resource('menus', UserMenuController::class);
        Route::resource('submenus', UserSubMenuController::class);
        Route::resource('roles', UserRoleController::class);
        Route::resource('employees', EmployeeController::class);
        Route::resource('products', ProductController::class);
        Route::resource('clients', ClientController::class);
        Route::resource('finance-coas', FinanceCoaController::class);
        Route::resource('finance-budgets', FinanceBudgetController::class);
        Route::resource('finance-transactions', FinanceTransactionController::class);
        Route::resource('finance-salaries', FinanceSalaryController::class);
        Route::resource('balance-beginnings', BalanceBeginningController::class);
        Route::resource('cms-contents', CmsContentController::class);
        
    });
    

});

app/Http/Controllers/FinanceTransactionController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\Models\FinanceCoa;
use Illuminate\Http\Request;
use App\Models\FinanceBudget;
use App\Models\BalanceBeginning;
use App\Models\BalanceRemaining;
use App\Models\FinanceTransaction;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Models\FinanceTransactionDetail;
use Yajra\DataTables\Facades\DataTables;

/**
 * Class FinanceTransactionController
 * @package App\Http\Controllers
 */
class FinanceTransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            return DataTables::of(FinanceTransaction::all())->toJson();
        }

        return view('finance-transaction.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $financeTransaction = new FinanceTransaction();
        return view('finance-transaction.create', compact('financeTransaction'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   

        $req = $request->all();
        $tahun = date('Y', strtotime($req['tanggal']));
        $backdate = false;
        if(strtotime($req['tanggal']) < strtotime(date('Y-m-d'))){
            $backdate = true;
        }

        if(
            !is_array($req['nomor_perkiraan'])
            || empty($req['tanggal'])
            || empty($req['jenis_transaksi'])
            || empty($req['tipe_transaksi'])
            || empty($req['keterangan'])
        ){
            return redirect()->route('finance-transactions.create')
            ->with('warning', 'The forms can not be EMPTY!');
        }

        // cek saldo awal
        $financeBudgetCount = FinanceBudget::where('tahun', $tahun)
        ->count();

        if($financeBudgetCount < 1){
            // harus input master anggarn tiap tahun
            return redirect()->route('finance-transactions.create')->with('warning', 'Anda belum input master anggaran tahun ini!');
        }

        foreach ($req['nomor_perkiraan'] as $key => $value) {

            $explode = explode(' - ', $value);
            $req['nomor_perkiraan'][$key] = $explode[0];
            $req['nama_akun'][$key] = $explode[1];

            // cek saldo anggaran

            // cek saldo anggaran
            $financeBudgetCount = FinanceBudget::where('tahun', $tahun)
            ->where('nomor_perkiraan', $explode[0])
            ->count();

            if($financeBudgetCount < 1){
                // harus input master anggarn tiap tahun
                return redirect()->route('finance-transactions.create')->with('warning', 'Anda belum input master anggaran pada akun '. $value .'!');
            }

            // cek saldo awal
            $balanceBeginningCount = BalanceBeginning::where('nomor_perkiraan', $explode[0])
            ->count();

            if($balanceBeginningCount < 1){
                // harus input master anggarn tiap tahun
                return redirect()->route('finance-transactions.create')->with('warning', 'Anda belum input saldo awal pada akun '. $value .'!');
            }
            
            // change format
            $req['debit'][$key] = preg_replace("/[^0-9.]/", "", $req['debit'][$key]);
            $req['kredit'][$key] = preg_replace("/[^0-9.]/", "", $req['kredit'][$key]);
        }
        
        $req['total_debit'] = preg_replace("/[^0-9.]/", "", $req['total_debit']);
        $req['total_kredit'] = preg_replace("/[^0-9.]/", "", $req['total_kredit']);

        $req['id_akun'] = 0;
        $req['tipe_akun'] = 'Umum';

        $data = FinanceTransaction::
        orderBy('id', 'desc')
        ->first();

        if(!empty($data)){
            
            $explode = explode('/', $data->nomor_voucher);
            $id = $explode[3] + 1;
            $id = sprintf('%04d',$id);

            $tahunVoucher = date('Y', strtotime($req['tanggal']));
            $dataTahun = FinanceTransaction::whereYear('tanggal', $tahunVoucher)
            ->orderBy('id', 'desc')
            ->first();

            if(!empty($dataTahun)){
                $explode = explode('/', $dataTahun->nomor_voucher);
            
                $id = $explode[3] + 1;
                $id = sprintf('%04d',$id);
            }else{
                $id = '0001';
            }
            
        }else{
            $id = '0001';
        }

        $id = sprintf('%04d',$id);

        if($req['jenis_transaksi'] == 'Pemasukan'){
            $jenisTransaksi = 'IN';
        }else{
            $jenisTransaksi = 'OUT';
        }

        if($req['tipe_transaksi'] == 'Kas'){
            $tipeTransaksi = 'CASH';
        }elseif($req['tipe_transaksi'] == 'Bank'){
            $tipeTransaksi = 'BANK';
        }else{
            $tipeTransaksi = 'EMONEY';
        }

        $voucher = $tipeTransaksi. "-". $jenisTransaksi. "/"."BCDY/".date('Y', strtotime($req['tanggal']))."/".$id;

        $req['nomor_voucher'] = $voucher;
        $req['pembuat'] = Auth::user()->name;
        
        $financeTransaction = FinanceTransaction::create($req);

        // grouping array
        // Cari akun yang sama
        // jika akun lawan sama, maka nilainya dijumlah 
        // data di merge jadi satu
        $acc = [];
            
        foreach ($req['nomor_perkiraan'] as $key => $nomor_perkiraan) {
            @$acc[$nomor_perkiraan]['nama_akun'][$req['remark'][$key]] = $req['nama_akun'][$key]; 
            @$acc[$nomor_perkiraan]['debit'][$req['remark'][$key]] += preg_replace("/[^0-9.]/", "", $req['debit'][$key]); 
            @$acc[$nomor_perkiraan]['kredit'][$req['remark'][$key]] += preg_replace("/[^0-9.]/", "", $req['kredit'][$key]); 
            @$acc[$nomor_perkiraan]['remark'][$req['remark'][$key]] = $req['remark'][$key]; 
        }

        // $key = nama_akun
        // jika remark sama disatuin, jika tidak ya tidak!
        foreach ($acc as $key => $value){
            foreach ($value['nama_akun'] as $k => $nm){
                $i = 0;
                FinanceTransactionDetail::create([
                    'finance_transaction_id' => $financeTransaction->id,
                    'nomor_perkiraan' => $key,
                    'nama_akun' => $acc[$key]['nama_akun'][$k],
                    'remark' => $acc[$key]['remark'][$k] ?? '-',
                    'debit' => $acc[$key]['debit'][$k] ?? '0',
                    'kredit' => $acc[$key]['kredit'][$k] ?? '0',
                    'jenis_transaksi' => $jenisTransaksi ?? '',
                    'tanggal' => $req['tanggal'] ?? ''
                ]);
                $i++;
            }
        }

        //===================================================================//

        if($backdate){
            
            // jika backdate maka akan generate ulang
            foreach ($req['nomor_perkiraan'] as $key => $noPerk){

                $coa = FinanceCoa::where('nomor_perkiraan', $noPerk)->first();
                $balanceRemaining = BalanceRemaining::where('nomor_perkiraan', $noPerk);
                
                // saldo anggaran disamakan
                $query = "

                    UPDATE finance_budgets 
                    SET saldo_sisa = saldo
                    WHERE nomor_perkiraan = '$noPerk'
                    AND tahun = '$tahun'

                ";

                DB::select($query);

                $balanceBeginning = BalanceBeginning::where('nomor_perkiraan', $noPerk);

                $balance = $balanceBeginning->first();

                $transaksi = BalanceRemaining::whereYear('tanggal', $tahun)
                ->where('nomor_perkiraan', '=', $noPerk)
                ->count();

                $saldo = $balance['nominal'];

                // hapus saldo sisa yang sudah masuk
                $balanceRemaining->delete();

                $kasir = FinanceTransactionDetail::where('nomor_perkiraan', $noPerk)
                ->orderBy('tanggal')
                ->get()
                ->toArray();                                   

                $dataAnggaran = FinanceTransactionDetail::where('nomor_perkiraan', $noPerk)
                ->where('jenis_transaksi', 'OUT')
                ->orderBy('tanggal')
                ->get()
                ->toArray();

                if(!empty($dataAnggaran)){
                    
                    foreach ($dataAnggaran as $key => $value){
    
                        $noPerk = $value['nomor_perkiraan'];
                        $tahunTransaksi =  date('Y', strtotime($value['tanggal']));
            
                        // budget 
            
                            // update saldo sisa di master anggaran
                            // update berdasarkan nominal yang ada masuk di kasir
                            // (prepare)
                            $nominalKasir = $value['debit'] + $value['kredit'];
            
                            // akun biasa
                            $anggaran = FinanceBudget::where('nomor_perkiraan', $noPerk)
                            ->where('tahun', $tahunTransaksi)
                            ->first();
            
                            $anggaranSisa = $anggaran['saldo_sisa'] - $nominalKasir; 
                        
                            // (update)
                            
                            // akun biasa
                            FinanceBudget::where('nomor_perkiraan', $noPerk)
                            ->where('tahun', $tahunTransaksi)
                            ->update([
                                'saldo_sisa' => $anggaranSisa
                            ]);
            
            
                        // end budget
                        

resources/views/finance-transaction/create.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Finance Transaction') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				@if ($message = Session::get('warning'))
					<div class="alert alert-warning">
						<p>{{ $message }}</p>
					</div>
				@endif

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('finance-transactions.store') }}"  role="form" enctype="multipart/form-data">
							@csrf
							
							@include('finance-transaction.form')

						</form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/finance-transaction/edit.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					<!--begin::Title-->
					<h3 class="text-dark fw-bolder my-1">{{ __('Finance Transaction') }}</h3>
					<!--end::Title-->
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ url('') }}" class="text-muted text-hover-primary">Home</a>
						</li>
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">Create</li>
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">

                @includeif('partials.errors')

				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
                        <form method="POST" action="{{ route('finance-transactions.update', $financeTransaction->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('finance-transaction.form')

                        </form>
					</div>
					</div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
<!--end::Main-->
@endsection

resources/views/finance-transaction/index.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
    <!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Finance Transaction') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
				<div class="card" >
					<div class="card-body">
						<!--begin::Alert-->                                        
					
					<!--end::Alert-->
						<div class="table-responsive">
							<a href="{{ route('finance-transactions.create') }}" class="btn btn-primary mb-3" >Tambah {{ __('Finance Transaction') }} Baru</a>
							@if ($message = Session::get('success'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
							<table id="dataTable" class="table table-row-bordered gy-5">
							</table>
						</div>
					</div>
                </div>
				<!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection

@section('scripts')
	<script type="text/javascript">


		$(document).ready(function(){
            var table = $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
				ajax: {
					url: "{{ route('finance-transactions.index') }}", 
					data: function ( d ) {
						d.test = 1;
					}
				},
                columns: 
				[
					{ 
						title: 'No',
						class: 'text-center',
                        data: 'id',
                        name: 'id'
                    },
					{
						title: 'Nomor Voucher',
						class: 'text-center',
                        data: 'nomor_voucher',
                        name: 'nomor_voucher'
                    },
					{
						title: 'Nominal',
						class: 'text-center',
                        data: 'total_debit',
                        name: 'total_debit',
						render: function(r) {
                            var data = rupiah2(r);
                            return 'Rp. <span style="float:right;">'+ data +'</span>';
                        }
                    },
                    {
						title: 'Tanggal',
						class: 'text-center',
                        data: 'tanggal',
                        name: 'tanggal'
                    },
					{
						title: 'Keterangan',
						class: 'text-center',
                        data: 'keterangan',
                        name: 'keterangan'
                    },
					{
						title: 'Pembuat',
						class: 'text-center',
                        data: 'pembuat',
                        name: 'pembuat'
                    },
					{
                        title: 'Action',
                        class: 'text-center',
                        data: 'id',
                        render: function(id, display, data) {
                            return `
                                <form action="{{ route('finance-transactions.destroy','') }}`+'/'+id+`" method="POST">
									<a class="btn btn-sm btn-primary " href="{{ route('finance-transactions.index') }}`+'/'+id+`"><i class="fa fa-fw fa-eye"></i> Show</a>
									<a class="btn btn-sm btn-warning " href="{{ route('finance-transactions.index') }}`+'/' +id+ '/print' +`"><i class="fa fa-fw fa-print"></i>Print</a>
									@csrf 
									@method('DELETE')
									<button type="submit" class="btn btn-danger btn-sm btn-delete" data-name="${data.nomor_voucher}"><i class="fa fa-fw fa-trash"></i> Delete</button>
								</form>
                            `;
                        }
                    },
                ],
				order: [0, 'desc']
            });

			table.on( 'draw.dt', function () {
                var info = table.page.info();
                var i = 0;
                for (let x = (info.start + 1); x <= info.end; x++) {
                    table.column(0).nodes()[i].innerHTML = x;
                    i++;
                }
            } ).draw();

			$('body').on('click', '.btn-delete', function(event) {
			event.preventDefault();

				var form = $(this).closest('form');

				var data = $(this).data('name');

				Swal.fire({
					title: 'Are you sure?',
					text: data + " will be deleted permanently!" ,
					icon: 'warning',
					showCancelButton: true,
					confirmButtonColor: '#3085d6',
					cancelButtonColor: '#d33',
					confirmButtonText: 'Yes, delete it!'
				}).then((result) => {
					if (result.isConfirmed) {

						$.ajax({
							type: form.attr('method'),
							url: form.attr('action'),
							data: form.serialize(),
							beforeSend: function(){
								Swal.fire({
									icon: 'info',
									title: 'Please wait....',
								});
							},
							success: function (r) {
								Swal.fire({
									icon: 'success',
									title: r.message
								});
								
								table.ajax.reload();
							},
							error: function (e) {
								Swal.fire({
									icon: 'error',
									title: 'An error occurred.'
								});
							},
						});
					}else{

						Swal.fire({
							icon: 'error',
							title: 'Operation canceled!'
						});
					}
				})


			});

        });

		

	</script>
@endsection

resources/views/finance-transaction/show.blade.php
@extends('layouts.main')
@section('title', __('Finance Transaction'))
@section('content')
<!--begin::Main-->
	<div class="d-flex flex-column flex-column-fluid">
		<!--begin::toolbar-->
		<div class="toolbar" id="kt_toolbar">
			<div class="container d-flex flex-stack flex-wrap flex-sm-nowrap">
				<!--begin::Info-->
				<div class="d-flex flex-column align-items-start justify-content-center flex-wrap me-1">
					
					<!--begin::Breadcrumb-->
					<ul class="breadcrumb breadcrumb-line bg-transparent text-muted fw-bold p-0 my-1 fs-7">
						<li class="breadcrumb-item">
							<a href="{{ route('finance-transactions.index') }}" class="text-muted text-hover-primary">{{ __('Finance Transaction') }}</a>
						</li>
						<li class="breadcrumb-item text-dark">{{ __('Finance Transaction') }}</li>							
					</ul>
					<!--end::Breadcrumb-->
				</div>
				<!--end::Info-->
				
				
			</div>
		</div>
		<!--end::toolbar-->
		<!--begin::Content-->
		<div class="content fs-6 d-flex flex-column-fluid mt-5" id="kt_content">
			<!--begin::Container-->
			<div class="container">
				<!--begin::Profile Account-->
                <div class="card">
                    <div class="card-header">
                        <div class="float-left mt-4">
                            <span class="card-title">Show Finance Transaction</span>
                        </div>
                        <div class="float-right mt-4">
                            <a class="btn btn-primary" href="{{ route('finance-transactions.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nomor Voucher:</strong>
                            {{ $financeTransaction->nomor_voucher }}
                        </div>
                        <div class="form-group">
                            <strong>Nominal:</strong>
                            Rp. {{ number_format($financeTransaction->total_debit, 2) }}
                        </div>
                        <div class="form-group">
                            <strong>Tanggal:</strong>
                            {{ $financeTransaction->tanggal }}
                        </div>
                        <div class="form-group">
                            <strong>Keterangan:</strong>
                            {{ $financeTransaction->keterangan }}
                        </div>
                        <div class="form-group">
                            <strong>Pembuat:</strong>
                            {{ $financeTransaction->pembuat }}
                        </div>
                        <div class="form-group">
                            <strong>Id Akun:</strong>
                            {{ $financeTransaction->id_akun }}
                        </div>
                        <div class="form-group">
                            <strong>Tipe Akun:</strong>
                            {{ $financeTransaction->tipe_akun }}
                        </div>

                    </div>
                </div>
            <!--end::Profile Account-->
			</div>
			<!--end::Container-->
		</div>
		<!--end::Content-->
	</div>
	<!--end::Main-->
@endsection